/*
 * Copyright 2017, NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * @file    board.h
 * @brief   Board initialization header file.
 */

/* This is an empty template for board specific configuration.*/

#ifndef _BOARD_H_
#define _BOARD_H_

#include "fsl_gpio.h"
#include "pin_mux.h"

/**
 * @brief	The board name
 */
#define BOARD_NAME "board"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */


#define BUZZER_ON 		GPIO_PinWrite(BOARD_INITPINS_BUZZER_GPIO, BOARD_INITPINS_BUZZER_PORT, BOARD_INITPINS_BUZZER_PIN, 1)
#define BUZZER_OFF 		GPIO_PinWrite(BOARD_INITPINS_BUZZER_GPIO, BOARD_INITPINS_BUZZER_PORT, BOARD_INITPINS_BUZZER_PIN, 0)
#define BUZZER_TOGGLE	GPIO_PortToggle(BOARD_INITPINS_BUZZER_GPIO, BOARD_INITPINS_BUZZER_PORT, BOARD_INITPINS_BUZZER_GPIO_PIN_MASK)

#define LED_VERDE_ON 		GPIO_PinWrite(BOARD_INITPINS_LED_VERDE_GPIO, BOARD_INITPINS_LED_VERDE_PORT, BOARD_INITPINS_LED_VERDE_PIN, 0)
#define LED_VERDE_OFF 		GPIO_PinWrite(BOARD_INITPINS_LED_VERDE_GPIO, BOARD_INITPINS_LED_VERDE_PORT, BOARD_INITPINS_LED_VERDE_PIN, 1)
#define LED_VERDE_TOGGLE	GPIO_PortToggle(BOARD_INITPINS_LED_VERDE_GPIO, BOARD_INITPINS_LED_VERDE_PORT, BOARD_INITPINS_LED_VERDE_GPIO_PIN_MASK)

#define LED_ROJO_ON 		GPIO_PinWrite(BOARD_INITPINS_LED_ROJO_GPIO, BOARD_INITPINS_LED_ROJO_PORT, BOARD_INITPINS_LED_ROJO_PIN, 0)
#define LED_ROJO_OFF 		GPIO_PinWrite(BOARD_INITPINS_LED_ROJO_GPIO, BOARD_INITPINS_LED_ROJO_PORT, BOARD_INITPINS_LED_ROJO_PIN, 1)
#define LED_ROJO_TOGGLE		GPIO_PortToggle(BOARD_INITPINS_LED_ROJO_GPIO, BOARD_INITPINS_LED_ROJO_PORT, BOARD_INITPINS_LED_ROJO_GPIO_PIN_MASK)

#define LCD_D4_ON			GPIO_PinWrite(BOARD_INITPINS_LCD_D4_GPIO, BOARD_INITPINS_LCD_D4_PORT, BOARD_INITPINS_LCD_D4_PIN, 1)
#define LCD_D4_OFF 			GPIO_PinWrite(BOARD_INITPINS_LCD_D4_GPIO, BOARD_INITPINS_LCD_D4_PORT, BOARD_INITPINS_LCD_D4_PIN, 0)

#define LCD_D5_ON			GPIO_PinWrite(BOARD_INITPINS_LCD_D5_GPIO, BOARD_INITPINS_LCD_D5_PORT, BOARD_INITPINS_LCD_D5_PIN, 1)
#define LCD_D5_OFF 			GPIO_PinWrite(BOARD_INITPINS_LCD_D5_GPIO, BOARD_INITPINS_LCD_D5_PORT, BOARD_INITPINS_LCD_D5_PIN, 0)

#define LCD_D6_ON			GPIO_PinWrite(BOARD_INITPINS_LCD_D6_GPIO, BOARD_INITPINS_LCD_D6_PORT, BOARD_INITPINS_LCD_D6_PIN, 1)
#define LCD_D6_OFF 			GPIO_PinWrite(BOARD_INITPINS_LCD_D6_GPIO, BOARD_INITPINS_LCD_D6_PORT, BOARD_INITPINS_LCD_D6_PIN, 0)

#define LCD_D7_ON			GPIO_PinWrite(BOARD_INITPINS_LCD_D7_GPIO, BOARD_INITPINS_LCD_D7_PORT, BOARD_INITPINS_LCD_D7_PIN, 1)
#define LCD_D7_OFF 			GPIO_PinWrite(BOARD_INITPINS_LCD_D7_GPIO, BOARD_INITPINS_LCD_D7_PORT, BOARD_INITPINS_LCD_D7_PIN, 0)

#define LCD_RS_ON			GPIO_PinWrite(BOARD_INITPINS_LCD_RS_GPIO, BOARD_INITPINS_LCD_RS_PORT, BOARD_INITPINS_LCD_RS_PIN, 1)
#define LCD_RS_OFF 			GPIO_PinWrite(BOARD_INITPINS_LCD_RS_GPIO, BOARD_INITPINS_LCD_RS_PORT, BOARD_INITPINS_LCD_RS_PIN, 0)

#define LCD_E_ON			GPIO_PinWrite(BOARD_INITPINS_LCD_E_GPIO, BOARD_INITPINS_LCD_E_PORT, BOARD_INITPINS_LCD_E_PIN, 1)
#define LCD_E_OFF 			GPIO_PinWrite(BOARD_INITPINS_LCD_E_GPIO, BOARD_INITPINS_LCD_E_PORT, BOARD_INITPINS_LCD_E_PIN, 0)


/**
 * @brief 	Initialize board specific settings.
 */
void BOARD_InitDebugConsole(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus */

#endif /* _BOARD_H_ */
