/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: LPC845
package_id: LPC845M301JBD64
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: '15', pin_signal: PIO1_0/CAPT_X1, label: LED_VERDE, identifier: LED_BLANCO;LED_VERDE}
- {pin_num: '18', pin_signal: PIO1_1/CAPT_X2, label: LED_ROJO, identifier: LED_ROJO}
- {pin_num: '20', pin_signal: PIO1_2/CAPT_X3, label: BUZZER, identifier: LED_BLANCO;BUZZER}
- {pin_num: '64', pin_signal: PIO1_10, label: LCD_D4, identifier: LCD_D4}
- {pin_num: '62', pin_signal: PIO1_11, label: LCD_D5, identifier: LCD_D5}
- {pin_num: '59', pin_signal: PIO1_21, label: LCD_D6, identifier: LCD_D6}
- {pin_num: '56', pin_signal: PIO1_20, label: LCD_D7, identifier: LCD_D7}
- {pin_num: '9', pin_signal: PIO1_12, label: LCD_RS, identifier: LCD_RS}
- {pin_num: '4', pin_signal: PIO0_12, label: LCD_E, identifier: LCD_E}
- {pin_num: '11', pin_signal: PIO1_13, label: LCD_RS, identifier: LCD_RS}
- {pin_num: '2', pin_signal: PIO0_13/ADC_10, label: LCD_RS, identifier: LCD_RS}
- {pin_num: '61', pin_signal: PIO0_18/ADC_8, label: MH_RXD, identifier: MH_RXD}
- {pin_num: '60', pin_signal: PIO0_19/ADC_7, label: MH_TXD, identifier: MH_TXD}
- {pin_num: '48', pin_signal: PIO0_0/ACMP_I1, label: MH_RX, identifier: MH_RX}
- {pin_num: '49', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: MH_TX, identifier: MH_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '15', peripheral: GPIO, signal: 'PIO1, 0', pin_signal: PIO1_0/CAPT_X1, identifier: LED_VERDE, direction: OUTPUT, gpio_init_state: 'true', mode: inactive}
  - {pin_num: '18', peripheral: GPIO, signal: 'PIO1, 1', pin_signal: PIO1_1/CAPT_X2, direction: OUTPUT, gpio_init_state: 'true', mode: inactive}
  - {pin_num: '64', peripheral: GPIO, signal: 'PIO1, 10', pin_signal: PIO1_10, direction: OUTPUT}
  - {pin_num: '62', peripheral: GPIO, signal: 'PIO1, 11', pin_signal: PIO1_11, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIO, signal: 'PIO1, 21', pin_signal: PIO1_21, direction: OUTPUT}
  - {pin_num: '56', peripheral: GPIO, signal: 'PIO1, 20', pin_signal: PIO1_20, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, direction: OUTPUT}
  - {pin_num: '2', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/ADC_10, direction: OUTPUT}
  - {pin_num: '48', peripheral: USART0, signal: RXD, pin_signal: PIO0_0/ACMP_I1}
  - {pin_num: '49', peripheral: USART0, signal: TXD, pin_signal: PIO0_14/ACMP_I3/ADC_2}
  - {pin_num: '20', peripheral: GPIO, signal: 'PIO1, 2', pin_signal: PIO1_2/CAPT_X3, identifier: BUZZER, direction: OUTPUT, gpio_init_state: 'false'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);

    gpio_pin_config_t LCD_E_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_E_GPIO, BOARD_INITPINS_LCD_E_PORT, BOARD_INITPINS_LCD_E_PIN, &LCD_E_config);

    gpio_pin_config_t LCD_RS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_13 (pin 2)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_RS_GPIO, BOARD_INITPINS_LCD_RS_PORT, BOARD_INITPINS_LCD_RS_PIN, &LCD_RS_config);

    gpio_pin_config_t LED_VERDE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO1_0 (pin 15)  */
    GPIO_PinInit(BOARD_INITPINS_LED_VERDE_GPIO, BOARD_INITPINS_LED_VERDE_PORT, BOARD_INITPINS_LED_VERDE_PIN, &LED_VERDE_config);

    gpio_pin_config_t LED_ROJO_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO1_1 (pin 18)  */
    GPIO_PinInit(BOARD_INITPINS_LED_ROJO_GPIO, BOARD_INITPINS_LED_ROJO_PORT, BOARD_INITPINS_LED_ROJO_PIN, &LED_ROJO_config);

    gpio_pin_config_t gpio1_pin1_2 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_2 (pin )  */
    GPIO_PinInit(GPIO, 1U, 2U, &gpio1_pin1_2);

    gpio_pin_config_t LCD_D4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_10 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_D4_GPIO, BOARD_INITPINS_LCD_D4_PORT, BOARD_INITPINS_LCD_D4_PIN, &LCD_D4_config);

    gpio_pin_config_t LCD_D5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_11 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_D5_GPIO, BOARD_INITPINS_LCD_D5_PORT, BOARD_INITPINS_LCD_D5_PIN, &LCD_D5_config);

    gpio_pin_config_t LCD_D7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_20 (pin 56)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_D7_GPIO, BOARD_INITPINS_LCD_D7_PORT, BOARD_INITPINS_LCD_D7_PIN, &LCD_D7_config);

    gpio_pin_config_t LCD_D6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO1_21 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_D6_GPIO, BOARD_INITPINS_LCD_D6_PORT, BOARD_INITPINS_LCD_D6_PIN, &LCD_D6_config);

    IOCON->PIO[36] = ((IOCON->PIO[36] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO1_0_MODE_INACTIVE));

    IOCON->PIO[37] = ((IOCON->PIO[37] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO1_1_MODE_INACTIVE));

    /* USART0_TXD connect to P0_14 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_14);

    /* USART0_RXD connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_0);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
